import '../css/painting.css'

const Painting = () => {
	return (
		<div className="painting col-12 d-flex justify-content-center">
			<div className="col-10">
				<p>quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos </p>
				<p>quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos </p>
				<p>quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos </p>
				<p>quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos </p>
				<p>quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos quadros marqavilhossos </p>
			</div>
		</div>
	)
}

export default Painting
